# Generated by Django 4.0.4 on 2022-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
