# Generated by Django 5.2.11 on 2026-02-06 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lastface_address_lastface_city_lastface_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_text', models.TextField()),
                ('alert_type', models.CharField(choices=[('help', 'Help Me'), ('save', 'Save Me'), ('emergency', 'Emergency'), ('danger', 'Danger'), ('other', 'Other')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='lastface',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
